---
- name: Install Multiple GitHub Repositories
  hosts: servers
  vars:
    repositories:
      - { vault_path: "altakleos/version-control/github/repositories/pysystemtrade" }
      - { vault_path: "altakleos/version-control/github/repositories/pysystemtrade_config" }
      - { vault_path: "altakleos/version-control/github/repositories/pysystemtrade_report" }
      - { vault_path: "altakleos/version-control/github/repositories/pysystemtrade_ecosystem" }
      - { vault_path: "altakleos/version-control/github/repositories/bc-utils" }

  tasks:
    - name: Install required packages
      become: yes
      apt:
        name:
          - git
        state: present

    - name: Install repositories from GitHub
      include_role:
        name: github_repo_installer
      vars:
        github_vault_path: "{{ item.vault_path }}"
      loop: "{{ repositories }}"
