---
- name: Ensure fstab entry for altakleos is present
  hosts: all
  become: yes
  tasks:
    - name: Ensure mount point directory exists
      file:
        path: /unraid-mnt/altakleos
        state: directory

    - name: Add altakleos entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        state: present
        line: "altakleos       /unraid-mnt/altakleos   9p      trans=virtio,version=9p2000.L,_netdev,rw        0       0"
        create: yes
      notify: mount altakleos

  handlers:
    - name: mount altakleos
      command: mount -a
      become: yes
